#############################################################################
# Makefile for building: MonoStudio
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  MonoStudio.pro
# Template: subdirs
# Command: F:\Qt\Qt5_14\5.14.2\mingw73_64\bin\qmake.exe -o Makefile MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = F:\Qt\Qt5_14\5.14.2\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = F:\Qt\Qt5_14\5.14.2\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = F:\Qt\Qt5_14\5.14.2\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-Tool-MonoToolkit \
		sub-Tool-MonoStylizedWindow \
		sub-MonoStudio


sub-Tool-MonoToolkit-qmake_all:  FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Tool\MonoToolkit\ && $(MAKE) -f Makefile qmake_all
sub-Tool-MonoToolkit: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Tool-MonoToolkit-make_first-ordered: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Tool-MonoToolkit-make_first: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Tool-MonoToolkit-all-ordered: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Tool-MonoToolkit-all: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Tool-MonoToolkit-clean-ordered: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Tool-MonoToolkit-clean: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Tool-MonoToolkit-distclean-ordered: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Tool-MonoToolkit-distclean: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Tool-MonoToolkit-install_subtargets-ordered: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Tool-MonoToolkit-install_subtargets: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Tool-MonoToolkit-uninstall_subtargets-ordered: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Tool-MonoToolkit-uninstall_subtargets: FORCE
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Tool-MonoStylizedWindow-qmake_all: sub-Tool-MonoToolkit-qmake_all FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd Tool\MonoStylizedWindow\ && $(MAKE) -f Makefile qmake_all
sub-Tool-MonoStylizedWindow: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-Tool-MonoStylizedWindow-make_first-ordered: sub-Tool-MonoToolkit-make_first-ordered  FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Tool-MonoStylizedWindow-make_first: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-Tool-MonoStylizedWindow-all-ordered: sub-Tool-MonoToolkit-all-ordered  FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Tool-MonoStylizedWindow-all: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-Tool-MonoStylizedWindow-clean-ordered: sub-Tool-MonoToolkit-clean-ordered  FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Tool-MonoStylizedWindow-clean: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-Tool-MonoStylizedWindow-distclean-ordered: sub-Tool-MonoToolkit-distclean-ordered  FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Tool-MonoStylizedWindow-distclean: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-Tool-MonoStylizedWindow-install_subtargets-ordered: sub-Tool-MonoToolkit-install_subtargets-ordered  FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Tool-MonoStylizedWindow-install_subtargets: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-Tool-MonoStylizedWindow-uninstall_subtargets-ordered: sub-Tool-MonoToolkit-uninstall_subtargets-ordered  FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-Tool-MonoStylizedWindow-uninstall_subtargets: FORCE
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MonoStudio-qmake_all: sub-Tool-MonoStylizedWindow-qmake_all FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd MonoStudio\ && $(MAKE) -f Makefile qmake_all
sub-MonoStudio: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MonoStudio-make_first-ordered: sub-Tool-MonoStylizedWindow-make_first-ordered  FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MonoStudio-make_first: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MonoStudio-all-ordered: sub-Tool-MonoStylizedWindow-all-ordered  FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MonoStudio-all: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MonoStudio-clean-ordered: sub-Tool-MonoStylizedWindow-clean-ordered  FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MonoStudio-clean: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MonoStudio-distclean-ordered: sub-Tool-MonoStylizedWindow-distclean-ordered  FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MonoStudio-distclean: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MonoStudio-install_subtargets-ordered: sub-Tool-MonoStylizedWindow-install_subtargets-ordered  FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MonoStudio-install_subtargets: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MonoStudio-uninstall_subtargets-ordered: sub-Tool-MonoStylizedWindow-uninstall_subtargets-ordered  FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MonoStudio-uninstall_subtargets: FORCE
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: MonoStudio.pro F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/qdevice.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/device_config.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/sanitize.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/g++-base.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/angle.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/qconfig.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qt_config.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/toolchain.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/default_pre.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/default_post.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qml_debug.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/warn_on.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/file_copies.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/exceptions.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/yacc.prf \
		F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/lex.prf \
		MonoStudio.pro
	$(QMAKE) -o Makefile MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/spec_pre.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/qdevice.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/device_config.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/sanitize.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/gcc-base.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/g++-base.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/angle.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/windows-vulkan.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/g++-win32.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/common/windows-desktop.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/qconfig.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/modules/qt_lib_zlib_private.pri:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qt_functions.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qt_config.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/win32-g++/qmake.conf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/exclusive_builds.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/toolchain.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/default_pre.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/win32/default_pre.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/resolve_config.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/default_post.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qml_debug.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/precompile_header.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/warn_on.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/qmake_use.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/file_copies.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/win32/windows.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/testcase_targets.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/exceptions.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/yacc.prf:
F:/Qt/Qt5_14/5.14.2/mingw73_64/mkspecs/features/lex.prf:
MonoStudio.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-Tool-MonoToolkit-qmake_all sub-Tool-MonoStylizedWindow-qmake_all sub-MonoStudio-qmake_all FORCE

make_first: sub-Tool-MonoToolkit-make_first-ordered sub-Tool-MonoStylizedWindow-make_first-ordered sub-MonoStudio-make_first-ordered  FORCE
all: sub-Tool-MonoToolkit-all-ordered sub-Tool-MonoStylizedWindow-all-ordered sub-MonoStudio-all-ordered  FORCE
clean: sub-Tool-MonoToolkit-clean-ordered sub-Tool-MonoStylizedWindow-clean-ordered sub-MonoStudio-clean-ordered  FORCE
distclean: sub-Tool-MonoToolkit-distclean-ordered sub-Tool-MonoStylizedWindow-distclean-ordered sub-MonoStudio-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-Tool-MonoToolkit-install_subtargets-ordered sub-Tool-MonoStylizedWindow-install_subtargets-ordered sub-MonoStudio-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Tool-MonoToolkit-uninstall_subtargets-ordered sub-Tool-MonoStylizedWindow-uninstall_subtargets-ordered sub-MonoStudio-uninstall_subtargets-ordered FORCE

sub-Tool-MonoToolkit-debug_ordered:
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-Tool-MonoStylizedWindow-debug_ordered: sub-Tool-MonoToolkit-debug_ordered 
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MonoStudio-debug_ordered: sub-Tool-MonoStylizedWindow-debug_ordered 
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-Tool-MonoToolkit-debug_ordered sub-Tool-MonoStylizedWindow-debug_ordered sub-MonoStudio-debug_ordered

sub-Tool-MonoToolkit-release_ordered:
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-Tool-MonoStylizedWindow-release_ordered: sub-Tool-MonoToolkit-release_ordered 
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MonoStudio-release_ordered: sub-Tool-MonoStylizedWindow-release_ordered 
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-Tool-MonoToolkit-release_ordered sub-Tool-MonoStylizedWindow-release_ordered sub-MonoStudio-release_ordered

sub-Tool-MonoToolkit-check_ordered:
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-Tool-MonoStylizedWindow-check_ordered: sub-Tool-MonoToolkit-check_ordered 
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MonoStudio-check_ordered: sub-Tool-MonoStylizedWindow-check_ordered 
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-Tool-MonoToolkit-check_ordered sub-Tool-MonoStylizedWindow-check_ordered sub-MonoStudio-check_ordered

sub-Tool-MonoToolkit-benchmark_ordered:
	@if not exist Tool\MonoToolkit\ mkdir Tool\MonoToolkit\ & if not exist Tool\MonoToolkit\ exit 1
	cd Tool\MonoToolkit\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoToolkit\MonoToolkit.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-Tool-MonoStylizedWindow-benchmark_ordered: sub-Tool-MonoToolkit-benchmark_ordered 
	@if not exist Tool\MonoStylizedWindow\ mkdir Tool\MonoStylizedWindow\ & if not exist Tool\MonoStylizedWindow\ exit 1
	cd Tool\MonoStylizedWindow\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\Tool\MonoStylizedWindow\MonoStylizedWindow.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MonoStudio-benchmark_ordered: sub-Tool-MonoStylizedWindow-benchmark_ordered 
	@if not exist MonoStudio\ mkdir MonoStudio\ & if not exist MonoStudio\ exit 1
	cd MonoStudio\ && ( if not exist Makefile $(QMAKE) -o Makefile E:\Project\MonoStudio\MonoStudio\MonoStudio.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-Tool-MonoToolkit-benchmark_ordered sub-Tool-MonoStylizedWindow-benchmark_ordered sub-MonoStudio-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

